apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\user\Documents\devops\kanban_app\kanban-board\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kanban-app
  name: kanban-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kanban-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\user\Documents\devops\kanban_app\kanban-board\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kanban-app
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: kanban-postgres
            - name: POSTGRES_DB
              value: kanban
            - name: POSTGRES_PASSWORD
              value: kanban
            - name: POSTGRES_USER
              value: kanban
          image: guettimouhsine/kanban:app
          name: kanban-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
