apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\user\Documents\devops\kanban_app\kanban-board\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kanban-ui
  name: kanban-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kanban-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\user\Documents\devops\kanban_app\kanban-board\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kanban-ui
    spec:
      containers:
        - image: guettimouhsine/kanban:ui
          name: kanban-ui
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
